домашнее задание модуль 11
v-kazantsev/Test-guru pull request #10
Opened 2018-01-24 12:10 UTC by v-kazantsev

2018-01-25 11:27 UTC, psylone requested changes

2018-01-25 11:27 UTC, psylone commented on Gemfile
> +gem 'bootstrap-sass', '~> 3.3', '>= 3.3.7'
Используй [официальный](https://getbootstrap.com/docs/4.0/getting-started/download/#rubygems) гем.

2018-01-25 11:27 UTC, psylone commented on app/controllers/admin/base_controller.rb
> +    unless current_user.is_a?(Admin)
Стоит сделать метод `current_user.admin?`

2018-01-25 11:27 UTC, psylone commented on app/controllers/concerns/welcome.rb
> +    after_action :welcome, only: [:create], if: :devise_controller?
Первый 2 консерна читаются хорошо, их обязанности понятны. Здесь нам нужно реализовать отображение флэш-сообщения после логина. При текущей реализации сообщение будет показываться для любого метода `create` из контроллера Devise. Будет работать, но трудно модифицировать. Нужно быть уверенным что метод `create` есть только в нужном нам контроллере Devise.

Кроме того, код будет выполняться после каждого действия (как минимум, проверка `devise_controller?`). Поэтому от этого модуля стоит отказаться. Лучше устанавливать это флэш-сообщение в каком-то одном явном месте - там где это действительно нужно (при успешном получении сессии пользователем).

2018-01-25 11:27 UTC, psylone commented on app/controllers/concerns/previous_url.rb
> +    def original_url
Будет ли работать это метод и где он используется?

2018-01-25 11:27 UTC, psylone commented on app/controllers/admin/tests_controller.rb
> +  @test = Test.new(test_params)
`current_user.created_tests.new(test_params)`.

2018-01-25 11:27 UTC, psylone commented on app/models/user.rb
> +  def first_name
Стоило хранить отдельно `first_name` и `last_name` в базе данных.

2018-01-25 11:27 UTC, psylone commented on app/views/admin/answers/_form.html.erb
> +<%= form_with model: [@question, @answer], local: true do |form| %>
Проверь создание/редактирование ответов.

2018-01-25 11:27 UTC, psylone commented on app/controllers/application_controller.rb
> +    admin_root_path
Для обычного пользователя получится лишний редирект: сначала он получить редирект на админскую базовую страницу, а затем - на базовую стринцу поскольку не является администратором. Стоит избавиться от лишнего перенаправления.

2018-01-25 12:48 UTC, v-kazantsev commented on Gemfile
> +gem 'bootstrap-sass', '~> 3.3', '>= 3.3.7'
Не смог заставить его с кастомными лэйаутами работать. Только сегодня разобрался.

2018-01-26 22:54 UTC, psylone approved these changes

2018-01-26 22:54 UTC, psylone commented on app/controllers/application_controller.rb
> +  end
Будет лучше сделать это методом модели. Почти наверняка это знание понадобится где-то ещё (не только в контроллере).

2018-01-26 22:54 UTC, psylone commented on app/controllers/session_controller.rb
> +  end
Нет необходимости переопределять методы из базового контроллера если не привносится нового поведения. То есть нет смысла переопределять метод и вызывать внутри только `super`. Если не переопределять метод, он автоматически будет вызван из базового контроллера.

2018-01-26 22:54 UTC, psylone commented on app/controllers/concerns/previous_url.rb
> +      cookies[:previous_url] = request.fullpath
Не критично, хоят `previous_url` устанавливается, но где он теперь используется? Поскольку мы явно направляем администраторов на `admin_root_path`, то для обычных пользователей как раз можно проверять есть ли `previous_url` и если нет, отправлять на `root_path`.

2018-01-26 22:54 UTC, psylone commented on app/controllers/concerns/previous_url.rb
> +      cookies[:previous_url] = request.fullpath
Можно использовать встроенную механику Devise: метод [`store_location_for`](http://www.rubydoc.info/gems/devise/Devise/Controllers/StoreLocation#store_location_for-instance_method).

2018-01-26 22:54 UTC, psylone commented on app/controllers/session_controller.rb
> +    end
Этот `end` закрывает метод, он должен быть отформатирован на 2 пробела левее.

2018-01-27 01:01 UTC, merged