домашнее задание модуль 14
v-kazantsev/Test-guru pull request #13
Opened 2018-01-30 08:48 UTC by v-kazantsev

2018-01-30 23:41 UTC, psylone requested changes

2018-01-30 23:41 UTC, psylone commented on app/services/gist_question_service.rb
> +    @client = client || GitHubClient.new
Логика понятна, но это уже лишнее. Если решили использовать официальный колиент, то он должен явно устанавливаться здесь. В `GitHubClient` больше нет необходимости.

2018-01-30 23:41 UTC, psylone commented on lib/clients/git_hub_client.rb
> +class GitHubClient
Этот класс больше не нужен.

2018-01-30 23:41 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +                )
Стоит создавать gist по ассоциации, например: `question.gists.create(user: current_user, gist_url: url)`.

2018-01-30 23:41 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +                gist_url: result[:files][:'testguru-question.txt'][:raw_url],
Можно сделать метод в сервисе чтобы здесь было `result.gist_url`.

2018-01-30 23:41 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    flash_options = status == 200 ? { notice: t('.success') } : { alert: t('.failure') }
Что за метод `status`?

2018-01-30 23:41 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    flash_options = status == 200 ? { notice: t('.success') } : { alert: t('.failure') }
Можно конечно создавать gist даже в том случае когда это действие завершилось с ошибкой чтобы фиксировать все попытки пользователя создать gist, хотя для нашей задачи это лишнее. Поэтому стоит создавать запись модели `Gist` только в том случае когда gist был успешно создан.

2018-01-30 23:41 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    flash[:info] = "#{view_context.link_to 'Your Gist', result[:files][:'testguru-question.txt'][:raw_url]}"
Достаточно одного флэш сообщения в случае успеха. Если выводится ссылка на gist, очевидно, что он успешно создан.

2018-01-30 23:41 UTC, psylone commented on db/schema.rb
> +    t.integer "user_id"
У пользователя стоит добавить ассоциацию на созданные им gists.

2018-01-30 23:41 UTC, psylone commented on app/views/admin/gists/index.html.erb
> +<% @gists.each do |gist| %>
Рендеринг коллекции стоит поместить во фрагмент представления.

2018-01-30 23:41 UTC, psylone commented on app/views/admin/gists/index.html.erb
> +  <td><%= link_to gist.gist_url %></td>
Предполагается что здесь выводится хэш gist-а в качестве отображаемого текста ссылки, например: `06b52f1e3194fec2b2356b9914fe4efe`.

2018-01-30 23:41 UTC, psylone commented on app/views/admin/gists/show.html.erb
> +<p><%= link_to 'Назад', admin_gists_path %></p>
Этот шаблон является избыточным, поскольку новой информации в нём нет.

2018-01-30 23:41 UTC, psylone commented on app/views/admin/gists/index.html.erb
> +  <td><%= truncate(gist.question.body, lenth: 25) { link_to 'дальше', admin_gist_path(gist) } %></td>
По клику на ссылку мы должны переходить на просмотр **вопроса**.

2018-01-31 01:27 UTC, v-kazantsev commented on app/controllers/test_passages_controller.rb
> +    flash_options = status == 200 ? { notice: t('.success') } : { alert: t('.failure') }
статус 200 и означает, что гист был успешно создан, разве нет?

2018-01-31 01:30 UTC, v-kazantsev commented on app/views/admin/gists/index.html.erb
> +  <td><%= truncate(gist.question.body, lenth: 25) { link_to 'дальше', admin_gist_path(gist) } %></td>
мы туда и переходим. ну согласен, затупил, вместо "дальше" надо было назвать как-нибудь типа "смотреть вопрос"

2018-01-31 23:04 UTC, psylone commented on app/views/admin/gists/index.html.erb
> +  <td><%= truncate(gist.question.body, lenth: 25) { link_to 'дальше', admin_gist_path(gist) } %></td>
Стоп, у нас же `admin_gist_path`, а это не просмотр вопроса, это новый шаблон просмотра gist-а.

2018-01-31 23:05 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    flash_options = status == 200 ? { notice: t('.success') } : { alert: t('.failure') }
Да, да, но сам метод `status` где определяется?

2018-01-31 23:38 UTC, psylone approved these changes

2018-01-31 23:38 UTC, psylone commented on app/controllers/admin/gists_controller.rb
> +    @gist.delete
На всякий случай, `delete` [не вызывает](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-delete) обратные вызовы модели.

2018-02-01 02:16 UTC, merged