Сделал таймер
v-kazantsev/Test-guru pull request #17
Opened 2018-02-19 09:50 UTC by v-kazantsev

Я как-то позабыл, что это два разных задания и свалил в кучу таймер и бэйджи. Бэйджи еще в процессе, их можно игнорировать. Большую часть кода таймера честно скопипастил.

2018-02-20 00:17 UTC, psylone requested changes

2018-02-20 00:17 UTC, psylone commented on app/assets/javascripts/utilities/countdown.js
> +    clock.innerHTML =
Лучше использовать `textContent`, будет работать быстрее.

2018-02-20 00:17 UTC, psylone commented on app/models/test_passage.rb
> +    self.current_question = next_question
Устанавливай следующий вопрос с помощью обратного вызова.

2018-02-20 00:17 UTC, psylone commented on app/models/test_passage.rb
> +  before_validation :set_first_question, on: :create
Используй единый обратный вызов для установки первого и следующиего вопроса, по сути, это одно и то же.

2018-02-20 00:17 UTC, psylone commented on app/assets/javascripts/utilities/countdown.js
> +  if (countdownTimer && countdownTimer.dataset.length > 0) {
Таймер либо есть, либо его нет. Лучше использовать этот признак, чем сравнение с `0`.

2018-02-22 04:18 UTC, v-kazantsev commented on app/models/test_passage.rb
> +  before_validation :set_first_question, on: :create
Было у меня сделано с обратным вызовом, там был какой-то баг, если в тесте было больше 3 вопросов, последний вопрос не отображался, где был баг, так и нашел, поэтому вернул как сейчас.

2018-02-22 04:21 UTC, v-kazantsev commented on app/assets/javascripts/utilities/countdown.js
> +  if (countdownTimer && countdownTimer.dataset.length > 0) {
Если  есть тесты, для которых таймер не установлен администратором, таймер на странице будет, но чтоб лишний раз скрипт не гонять, я эту проверку и делаю.

2018-02-24 00:30 UTC, psylone commented on app/assets/javascripts/utilities/countdown.js
> +  if (countdownTimer && countdownTimer.dataset.length > 0) {
Понятно, но то что таймер на странице будет хотя он не установлен выглядит странно.

2018-02-24 00:31 UTC, psylone commented on app/models/test_passage.rb
> +  before_validation :set_first_question, on: :create
Ясно.

2018-02-24 00:37 UTC, psylone requested changes

2018-02-24 00:37 UTC, psylone commented on app/models/badge.rb
> +  after_initialize :set_default_image
Это нужно делать перед созданием записи в базе. Либо у нас есть URL с картинкой, либо генерируем по умолчанию и создаём новую запись в таблице.

2018-02-27 12:21 UTC, psylone requested changes

2018-02-27 12:21 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    calculate_tests_passed
Лучше не выносить в данном случае это в модуль, поскольку данная логика тесно связана с контекстом метода контроллера. К тому же, вряд ли мы еще где-то будем считать количество успешно пройденных тестов.

2018-02-27 12:21 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    Awards.new(@test_passage).call if @test_passage.result > 85
Интерфейс верный, если метод `call` не вызывается значит дело в условии.

2018-02-27 12:21 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    calculate_tests_passed
Мы, кстати, сюда можем прийти по истечению таймаута если у теста выставлен таймер. Тогда это будет уже не успешно пройденный тест. Как посмотреть конечно, пользователь мог набрать нужное количество правильных ответов. В общем, стоит иметь в виду этот момент.

2018-02-27 12:21 UTC, psylone commented on app/operations/awards.rb
> +      byebug
`Badge.all.each {}`.

2018-02-27 13:39 UTC, v-kazantsev commented on app/controllers/test_passages_controller.rb
> +    calculate_tests_passed
Пока что у меня таймер привязан к своему экшену, буду с ним разбираться когда закончу с бэйджами. там еще по скрипту есть вопросы.

2018-02-27 21:57 UTC, psylone approved these changes

2018-02-27 21:57 UTC, psylone commented on app/operations/awards.rb
> +        award!(@test_passage, badge) if badge.passed_times_rule?(@test_passage, badge.rule_value)
Раз у нас `@test_passage` инстанс-переменная, можно её здесь не передавать в качестве аргумента.

2018-02-27 21:57 UTC, psylone commented on app/operations/awards.rb
> +    test_passage.user.save
`save` вызывать не нужно.

2018-02-28 23:09 UTC, psylone requested changes

2018-02-28 23:09 UTC, psylone commented on app/views/test_passages/show.html.erb
> +        .pagecontainer {display:none;}
Это не сработает потому что физически HTML элемент уже будет в DOM дереве. Можно в инспекторе изменить свойство `display: none;` и все увидеть.

2018-02-28 23:09 UTC, psylone commented on app/views/test_passages/show.html.erb
> +        .pagecontainer {display:none;}
Кроме того, запросы можно выполнять руками из консоли или HTTP-клиента такого как Postman, например.

2018-02-28 23:09 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    if @test_passage.result > 85
Стоит сделать метод `success?` в модели.

2018-02-28 23:09 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +  def end_by_timeout
Так где сейчас вызывается этот метод?

2018-02-28 23:15 UTC, psylone commented
> По поводу проверки if (countdownTimer && countdownTimer.dataset.length > 0)
> нам в любом случае надо делать проверку, включен ли таймер для текущего теста, почему бы их не совместить? если таймер для теста не назначен, он не отображается.

Что значит включен? Таймир либо установлен (и тогда должен быть > 0), либо не установлен и тогда его в принципе не должно быть.

2018-03-01 21:47 UTC, psylone approved these changes

2019-05-17 09:39 UTC, closed without merging