Module 4.Интерфейс запросов AR
v-kazantsev/Test-guru pull request #3
Opened 2017-12-13 08:45 UTC by v-kazantsev

2017-12-13 18:10 UTC, psylone requested changes

2017-12-13 18:10 UTC, psylone commented on db/seeds.rb
> +end
Метод `create` может принимать [массив](http://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-create) аргументов.

2017-12-13 18:10 UTC, psylone commented on app/models/user.rb
> +    end
У тебя здесь множество SQL запросов получится. Попробуй использовать соединение с помощью метода `joins`.

2017-12-13 18:10 UTC, psylone commented on app/models/test.rb
> +      )
Проверь пожалуйста результат когда передаётся название категории которая не существует в базе. И пожалуйста попробуй переписать метод так чтобы отправлялся единственный SQL запрос.

2017-12-14 23:06 UTC, psylone requested changes

2017-12-14 23:06 UTC, psylone commented on app/models/user.rb
> +    User.joins(:tests).where(tests: { level: level })
Пожалуйста проверь как работает этот метод. Нам нужно получить коллекцию тестов. Кроме того, сейчас соединение происходит между всеми пользователями и тестами которые они проходят. Нам же нужно получить тесты которые проходит один конкретный текущий пользователь. По этой причине в задании говорится об инстанс-методе.

2017-12-14 23:06 UTC, psylone commented on app/models/test.rb
> +  scope :order_by_title, -> { order title: :desc }
Можно не создавать для этого скоуп: `Test.order(title: :desc)` выглядит окей.

2017-12-14 23:06 UTC, psylone commented on app/models/test.rb
> +  end
Проверь пожалуйста как работает метод когда мы передаём название категории которой не существует в нашей базе данных.

2017-12-14 23:06 UTC, psylone commented on app/models/test.rb
> +  end
Используй соединение чтобы отправлялся единственный SQL запрос. То есть, нам нужно построить соединение с отношением категорий, затем выбрать только те кортежи название категории в которых совпадает с заданным и затем выбрать только название тестов с сортировкой по убыванию. И это должен быть один SQL запрос.

2017-12-14 23:06 UTC, psylone commented on app/models/test.rb
> +  end
Либо ты можешь использовать то решение которое есть сейчас, но вызвать метод `where` у модели `Category`. В этом случае ActiveRecord будет использовать подзапрос.

2017-12-15 07:29 UTC, v-kazantsev commented on app/models/test.rb
> +  end
Когда мы передаем название категории, которой не существует в базе, вызывается исключение. Что должно быть на самом деле - не знаю.

2017-12-15 07:29 UTC, v-kazantsev commented on app/models/test.rb
> +  scope :order_by_title, -> { order title: :desc }
Надо же было проверить как это работает.

2017-12-15 12:08 UTC, psylone commented on app/models/test.rb
> +  end
Да! Исключение выдаётся потому что мы используем `find_by!` с восклицательным знаком. Если мы пытаемся выбрать данные на основе какого-то критерия, и таких данных нет - нужно вернуть пустую коллекцию. Конечно, поведение системы в этом случае во многом зависит от конкретной задачи, но в данном случае лучше вернуть пустой массив вместо исключения.

2017-12-15 12:10 UTC, psylone commented on app/models/test.rb
> +  scope :order_by_title, -> { order title: :desc }
Такая возможность ещё представится )

2017-12-15 22:48 UTC, psylone approved these changes

2017-12-15 22:48 UTC, psylone commented on app/models/user.rb
> +    self.tests.where(level: level)
Правильная идея, но без соединительной таблицы ассоциация работать не будет. Поэтому нужно создать соединительную таблицу с помощью миграции.

2018-01-08 02:14 UTC, merged