Домашнее задание к модулю 6
v-kazantsev/Test-guru pull request #5
Opened 2018-01-10 08:59 UTC by v-kazantsev

### Изменил атрибут "password" у пользователя на "email" и перезалил базу с rails db:setup
- добавил валидации в соответствующие модели
- добавил скоупы (не смог подобрать правильный метод для валидации входит ли уровень в рэндж (5..Float::INFINITY), пришлось оставить просто >=5)
- изменил методы класса из задания к 4 модулю на скоупы

2018-01-10 22:32 UTC, psylone requested changes

2018-01-10 22:32 UTC, psylone commented on app/models/test.rb
> +  scope :by_category, -> (category) { where(category_id: Category.id_by_name(category)) }
Обычно эту задачу решают через `joins`.

2018-01-10 22:32 UTC, psylone commented on app/models/category.rb
> +  scope :id_by_name, -> (name) { where(title: name).ids }
Этот скоуп довольно сомнителен. Один идентификатор нам возвращается или несколько? Почему мы решили вообще сделать отдельный скоуп для получения идентификаторов. Если идти этим путём, скоуп следует сделать `by_name`, а выше где он используется если нужно получить идентификаторы - вызвать `pluck`.

2018-01-10 22:32 UTC, psylone commented on app/models/user.rb
>    def get_test_by_level(level)
Имя метода предполагает то вернется один тест, хотя это не так.

2018-01-10 22:32 UTC, psylone commented on app/models/user.rb
>    def get_test_by_level(level)
Можно в принципе обойтись без этого метода вовсе, ассоциации и `where` достаточно. Либо можно завести скоуп `by_level` в модели теста.

2018-01-10 22:32 UTC, psylone commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level }
Нужен составной уникальный индекс.

2018-01-10 22:32 UTC, psylone commented on app/models/test.rb
> +  # end
Используй созданные скоупы в данном методе. Также обрати внимание на название метода: его суть в том что он возвращает именно _названия тестов_.

2018-01-10 22:32 UTC, psylone commented on app/models/test.rb
> +  validates :level, numericality: { only_integer: true, greather_than: 0 }
Валидация должна срабатывать не только на нижнюю границу условия, но и на верхнюю.

2018-01-10 22:32 UTC, psylone commented on app/models/question.rb
> +  validate :answers, if: :in_range
Метод предиката должен отвечать строго за проверку условия должна ли выполняться валидация. Сама валидация - это отдельный метод.

2018-01-10 22:32 UTC, psylone commented on app/models/test.rb
> +  #belongs_to :author
Это необходимо доработать )

2018-01-11 02:20 UTC, v-kazantsev commented on app/models/test.rb
> +  validates :level, numericality: { only_integer: true, greather_than: 0 }
Я нашел только одно определение положительным числам - это числа больше 0, про верхнюю границу ничего не сказано. Вообще по нашим критериям если у нас есть тесты с уровнем 0, то они эту проверку не пройдут т.к. 0 не является положительным числом.

2018-01-11 03:24 UTC, v-kazantsev commented on app/models/user.rb
>    def get_test_by_level(level)
это из задания к 4 модулю

2018-01-11 10:57 UTC, psylone commented on app/models/test.rb
> +  validates :level, numericality: { only_integer: true, greather_than: 0 }
Прошу прощения, не посмотрел на атрибут. Имел в виду проверку на количество ответов.

2018-01-11 10:58 UTC, psylone commented on app/models/user.rb
>    def get_test_by_level(level)
Да, но теперь есть ассоциации и скоупы и отдельный метод в модели для этой логики можно не держать.

2018-01-11 19:14 UTC, psylone requested changes

2018-01-11 19:14 UTC, psylone commented on app/models/test.rb
> +  scope :by_category, -> (category) { where(category_id: Category.joins(:tests).where(title: category)).order(title: :desc).pluck(:title) }
Скоуп называется `by_category`, поэтому ожидается что вернется коллекция объектов категорий. Дальше уже можно написать: `Test.by_category('Ruby').order(title: :desc).pluck(:title)`.

2018-01-11 19:14 UTC, psylone commented on app/models/test.rb
> +  scope :by_category, -> (category) { where(category_id: Category.joins(:tests).where(title: category)).order(title: :desc).pluck(:title) }
`joins` лучше вызывать у текущей модели:

```ruby
scope :by_category, -> (category_title) { joins(:category).where(categories: { title: category_title }) }
```

2018-01-11 19:14 UTC, psylone commented on my_index
> +      create    db/migrate/20180111031922_add_index.rb
Что это за файл (и ещё один ниже)?

2018-01-11 19:14 UTC, psylone commented on app/models/question.rb
> +    end
Получается что вопрос без ответа сохранить мы не можем. В принципе, это норм. Но остаётся другая проблема: мы можем создать объект класса `Answer` и привязать его к существующему вопросу даже если у этого вопроса уже есть 4 ответа.

2018-01-12 02:12 UTC, v-kazantsev commented on app/models/test.rb
> +  scope :by_category, -> (category) { where(category_id: Category.joins(:tests).where(title: category)).order(title: :desc).pluck(:title) }
А почему? Если это inner join aka пересечение, какая разница? Просто по-моему joins на родительской таблице проще воспринимается.

2018-01-12 02:14 UTC, v-kazantsev commented on my_index
> +      create    db/migrate/20180111031922_add_index.rb
Вообще не представляю, откуда он взялся. Пытался заставить подхватить миграцию с составным индексом, в конце концов плюнул и сделал руками.

2018-01-12 10:17 UTC, psylone commented on app/models/test.rb
> +  scope :by_category, -> (category) { where(category_id: Category.joins(:tests).where(title: category)).order(title: :desc).pluck(:title) }
На самом деле нет, ведь мы выбираем именно тесты, но для определённой категории. Для этого мы как раз строим соединение таблицы тестов с таблицей категорий.

2018-01-12 10:21 UTC, psylone approved these changes

2018-01-12 10:21 UTC, psylone commented on app/models/answer.rb
> +    errors.add(:question, 'Too many answers') if question.answers.count > 4
Здесь стоит взять строгое неравенство, иначе на момент создания ответа если у вопроса уже есть 4 ответа, `4 > 4` вернёт `false` и будет создан 4-й ответ.

2018-01-12 11:18 UTC, v-kazantsev commented on app/models/answer.rb
> +    errors.add(:question, 'Too many answers') if question.answers.count > 4
тут не понял.  проверял так
q = Question.first
q.answers.count => 3 (так в seed сделано)
Answer.create! (body: "Lorem ipsum", question_id: 1)
q.answers.count => 4
Answer.create! (body: "Lorem ipsum", question_id: 1)
ошибка "Too many answers"
Вроде бы работает как и должно

2018-01-13 05:56 UTC, merged

2018-01-15 17:26 UTC, psylone commented on app/models/answer.rb
> +    errors.add(:question, 'Too many answers') if question.answers.count > 4
Что-то здесь не так. У меня вот такая валидация ведёт себя некорректно.

2018-01-15 17:32 UTC, psylone commented on app/models/answer.rb
> +    errors.add(:question, 'Too many answers') if question.answers.count > 4
Твой пример тоже не работает:

```ruby
firefly:Test-guru psylone$ bin/rails c
Running via Spring preloader in process 45865
Loading development environment (Rails 5.1.4)
irb(main):001:0> q = Question.first
  Question Load (0.5ms)  SELECT  "questions".* FROM "questions" ORDER BY "questions"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> #<Question id: 1, body: "Demonstrate two ways to create an empty hash", test_id: 1, created_at: "2018-01-15 17:30:25", updated_at: "2018-01-15 17:30:25">
irb(main):002:0> q.answers.count
   (0.6ms)  SELECT COUNT(*) FROM "answers" WHERE "answers"."question_id" = ?  [["question_id", 1]]
=> 3
irb(main):004:0> Answer.create!(body: "Lorem ipsum", question_id: 1)
   (0.2ms)  begin transaction
  Question Load (0.1ms)  SELECT  "questions".* FROM "questions" WHERE "questions"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
   (0.1ms)  SELECT COUNT(*) FROM "answers" WHERE "answers"."question_id" = ?  [["question_id", 1]]
  SQL (0.8ms)  INSERT INTO "answers" ("body", "question_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["body", "Lorem ipsum"], ["question_id", 1], ["created_at", "2018-01-15 17:31:02.404867"], ["updated_at", "2018-01-15 17:31:02.404867"]]
   (0.7ms)  commit transaction
=> #<Answer id: 16, body: "Lorem ipsum", question_id: 1, created_at: "2018-01-15 17:31:02", updated_at: "2018-01-15 17:31:02", correct: false>
irb(main):005:0> q.answers.count
   (0.2ms)  SELECT COUNT(*) FROM "answers" WHERE "answers"."question_id" = ?  [["question_id", 1]]
=> 4
irb(main):006:0> Answer.create!(body: "Lorem ipsum", question_id: 1)
   (0.1ms)  begin transaction
  Question Load (0.2ms)  SELECT  "questions".* FROM "questions" WHERE "questions"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
   (0.1ms)  SELECT COUNT(*) FROM "answers" WHERE "answers"."question_id" = ?  [["question_id", 1]]
  SQL (0.3ms)  INSERT INTO "answers" ("body", "question_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["body", "Lorem ipsum"], ["question_id", 1], ["created_at", "2018-01-15 17:31:15.485681"], ["updated_at", "2018-01-15 17:31:15.485681"]]
   (1.1ms)  commit transaction
=> #<Answer id: 17, body: "Lorem ipsum", question_id: 1, created_at: "2018-01-15 17:31:15", updated_at: "2018-01-15 17:31:15", correct: false>
irb(main):007:0> q.answers.count
   (0.2ms)  SELECT COUNT(*) FROM "answers" WHERE "answers"."question_id" = ?  [["question_id", 1]]
=> 5
```

2018-01-15 17:32 UTC, psylone commented on app/models/answer.rb
> +    errors.add(:question, 'Too many answers') if question.answers.count > 4
Сделай пожалуйста `bin/rails db:reset` и проверь снова.

2018-01-16 03:20 UTC, v-kazantsev commented on app/models/answer.rb
> +    errors.add(:question, 'Too many answers') if question.answers.count > 4
Получается, что если мы проверяем question на количество ответов либо на валидность (через validates_associated), то проверка проходит ПЕРЕД созданием ответа и 5й ответ будет создаваться. Единственное, что приходит в голову - проверять, что у вопроса менее 4 ответов на момент создания ответа.

2018-01-21 12:57 UTC, psylone commented on app/models/answer.rb
> +    errors.add(:question, 'Too many answers') if question.answers.count > 4
> Получается, что если мы проверяем question на количество ответов либо на валидность (через validates_associated), то проверка проходит ПЕРЕД созданием ответа и 5й ответ будет создаваться.

Здесь несколько особенностей. Прежде всего, если мы создаём связанный объект через ассоциацию, то есть, ответ через вопрос, то этот объект добавляется в коллекцию, затем происходит логика валидаций и сохранения. Однако, метод `count` всегда отправляет прямой запрос в БД. Поэтому если мы, например, добавили 5-й ответ к вопросу (до момента валидаций), но в валидации у нас метод `answers.count`, то он вернёт актуальное количество ответов которые уже есть в БД. Поскольку 5-й ответ ещё не сохранён, вернётся 4.

Так или иначе, текущее решение в ветке `master` - верное.