Домашнее задание к модулю 7
v-kazantsev/Test-guru pull request #6
Opened 2018-01-13 06:09 UTC by v-kazantsev

- создал вложенные ресурсы в *routes*
- создал контроллер *questions*
- создал в нем экшены *index*, *create* и *destroy*
- добавил коллбэк для поиска теста
- добавил обработку исключения "запись не найдена"

2018-01-13 14:22 UTC, psylone requested changes

2018-01-13 14:22 UTC, psylone commented on app/controllers/questions_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found
Стоит вынести обработчик выше в базовый класс, поскольку этот обработчик ловит исключение общего характера (когда объект не найден в базе данных).

2018-01-13 14:22 UTC, psylone commented on config/routes.rb
> +  resources :questions
Используй опцию `shallow`. Для 2-х уровней вложенности можно обойтись и без нее, но когда появятся ответы, `shallow` очень пригодится.

2018-01-13 14:22 UTC, psylone commented on app/models/question.rb
> +    if self.answers.size < 1 || self.answers.size > 4
Предыдущий вариант работал также.

2018-01-13 14:22 UTC, psylone commented on app/controllers/questions_controller.rb
> +    render plain: "Вопросы к тесту №#{params[:test_id]}"
Если мы возвращаем список ответов, то именно список ответов и нужно возвращать. Он может быть в виде простого текста или HTML, но точно пользователь не ожидает получить в ответе текст _Вопросы к тесту №1_.

2018-01-13 14:22 UTC, psylone commented on app/controllers/questions_controller.rb
> +    render html: "<h2>Вопрос №#{params[:id]}</h2>".html_safe
Здесь то же что выше: нужно вернуть сам вопрос, например его содержимое, но точно не идентификатор.

2018-01-13 14:22 UTC, psylone commented on app/controllers/questions_controller.rb
> +  def create
Как ты проверял что этот метод работает?

2018-01-13 14:22 UTC, psylone commented on app/controllers/questions_controller.rb
> +    @cquestion = @test.questions.find(params[:id])
Можно сделать ещё один коммит в эту же ветку, и он автоматически попадёт в пулл-реквест.

2018-01-13 14:22 UTC, psylone commented on app/controllers/questions_controller.rb
> +    render plain: "Вопросы к тесту №#{params[:test_id]}"
Также прими во внимание что нам интересен список всех вопросов для конкретного теста.

2018-01-13 14:22 UTC, psylone commented on app/controllers/questions_controller.rb
> +  def create
В задании явно это не указано, но подразумевается что у тебя будет форма HTML для того чтобы можно было создать вопрос из браузера.

2018-01-14 02:05 UTC, v-kazantsev commented on app/models/question.rb
> +    if self.answers.size < 1 || self.answers.size > 4
Мне кажется, второй вариант для понимания проще.

2018-01-14 02:44 UTC, v-kazantsev commented on app/controllers/questions_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found
Но тогда, наверное, стоит выводить сообщение не "вопрос не найден" а что-то общее типа "объект не найден" да и сам метод тогда назвать rescue_with_object_not_found ?

2018-01-14 23:15 UTC, psylone commented on app/models/question.rb
> +    if self.answers.size < 1 || self.answers.size > 4
Может и так, но будет 2 SQL запроса вместо одного.

2018-01-14 23:16 UTC, psylone commented on app/controllers/questions_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found
Да, разумно.

2018-01-14 23:20 UTC, psylone approved these changes

2018-01-14 23:20 UTC, psylone commented on app/controllers/questions_controller.rb
> +    end
`@test.questions.pluck(:body)`.

2018-01-14 23:20 UTC, psylone commented on app/controllers/questions_controller.rb
> +    @test = Test.find(1)
Почему внезапно `Test.find(1)`? А если вопрос не этом тесту принадлежит?

Суть в том что мы благодаря `shallow` получаем прямой идентификатор вопроса из URL и можем его использовать: `Question.find(params[:id])`. Искать тест при этом нет необходимости. Посмотри ещё раз вывод команды `bin/rails routes` и проанализируй какие параметры доступны для существующих URL.

2018-01-14 23:20 UTC, psylone commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.find(params[:id])
То же что выше.

2018-01-15 02:10 UTC, merged