Домашнее задание модуль 8
v-kazantsev/Test-guru pull request #7
Opened 2018-01-15 08:46 UTC by v-kazantsev

- Создал контроллер test и соответствующие экшены в нем
- Реализовал отображение вопросов к тесту и форму для создания нового вопроса
- Добавил ссылки для навигации
- Добавил футер
- Добавил хелперы
- Реализовал отображение кастомного заголовка страницы для формы редактирования вопроса. Для формы создания вопрос не сделал так как для нее нет отдельной страницы.

2018-01-15 18:03 UTC, psylone requested changes

2018-01-15 18:03 UTC, psylone commented on app/views/tests/show.html.erb
> +  <% @test.questions.each do |question| %>
Вынеси рендеринг коллекции вопросов во фрагмент представления.

2018-01-15 18:03 UTC, psylone commented on app/views/layouts/application.html.erb
> +    <title><%= @page_title %></title>
Используй [`content_for`](http://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-content_for).

2018-01-15 18:03 UTC, psylone commented on app/helpers/tests_helper.rb
> +  Time.now.year
Используй метод `Time.current`, вместо `Time.now` чтобы принять во внимание часовой пояс сконфигурированный в приложении.

2018-01-15 18:03 UTC, psylone commented on app/controllers/questions_controller.rb
>  # Модуль 7 Задание 2 Вопрос 2,5
Что за `Test.find(1)`?

2018-01-15 18:03 UTC, psylone commented on app/controllers/questions_controller.rb
>    end
Список вопросов выводится на странице просмотра теста, поэтому данный метод нам не нужен.

2018-01-15 18:03 UTC, psylone commented on app/controllers/questions_controller.rb
>  #
Проверь выше в методе `create` как выводятся ошибки в форме при создании вопроса.

2018-01-15 18:03 UTC, psylone commented on app/views/tests/_new_question_form.html.erb
> +<% end %>
Почему форма создания нового вопроса находится в ресурсе тестов?

2018-01-15 18:03 UTC, psylone commented on app/views/tests/_new_question_form.html.erb
> +  <%= render 'shared/errors', resource: @test %>
Проверь вывод ошибок при создании вопроса.

2018-01-15 18:03 UTC, psylone commented on app/helpers/application_helper.rb
> +  end
Скорее этот хэлпер относится к вопросам, чем ко всему приложению.

2018-01-15 18:03 UTC, psylone commented on app/helpers/application_helper.rb
> +  end
Также логичней в качестве параметра принимать объект вопроса, ведь это `question_header`, а не `test_header`.

2018-01-15 18:03 UTC, psylone commented on app/helpers/application_helper.rb
> +  end
Кроме того, хэлпер должен сам разруливать ситуацию со стейтом вопроса. То есть в зависимости от того новый ли у нас вопрос или уже существующий хэлпер должен возвращать правильный заголовок.

2018-01-15 18:03 UTC, psylone commented on app/helpers/tests_helper.rb
> +  "https://github.com/" + "#{author}" +"/" + "#{repo}"
Используй интерполяцию: `"https://github.com/#{author}/#{repo}"`.

2018-01-15 18:03 UTC, psylone commented on app/helpers/tests_helper.rb
> +end
Это скорее общий хэлпер, чем хэлпер тестов.

2018-01-15 18:03 UTC, psylone commented on app/helpers/tests_helper.rb
> +end
Обычно так называются методы которые Rails создаёт автоматически на основе объявленных нами маршрутов. Чтобы не было путаницы лучше отказаться от данного метода и указывать URL в `link_to`.

2018-01-15 18:03 UTC, psylone commented on app/helpers/tests_helper.rb
> +end
То есть по факту данный метод не берёт на себя никакую обязанность и нам без разницы использовать строку или метод который возвращает эту же строку.

2018-01-15 18:03 UTC, psylone commented on app/views/layouts/_footer.html.erb
> +<%= link_to "Проект Тест-гуру", github_url("v-kazantsev", "Test-guru") %>
Сделай так чтобы хэлпер можно было использовать так:

```ruby
<%= github_url('v-kazantsev', 'Test-guru') %>
```

2018-01-15 18:03 UTC, psylone commented on app/views/questions/_edit_form.html.erb
> +<% @page_title = "Edit" + question_header(@question.test) %>
Хэлпер `question_header` должен возвращать заголовок полностью иначе в нём не будет особого смысла.

2018-01-15 18:03 UTC, psylone commented on app/views/questions/_edit_form.html.erb
> +<% end %>
Это должен быть фрагмент `_form.html.erb`. Шаблон `edit.html.erb` у тебя уже есть.

2018-01-15 18:03 UTC, psylone commented on app/views/tests/_new_question_form.html.erb
> +<% end %>
Нет смысла повторять форму для создания вопроса поскольку фактически она такая же как и форма для редактирования вопроса.

2018-01-16 23:43 UTC, psylone approved these changes

2018-01-16 23:43 UTC, psylone commented on app/controllers/questions_controller.rb
> +    @question = Question.new
Лучше сделать так: `@question = @test.questions.new` на всякий случай чтобы можно было в шаблоне обратиться к тесту `@question.test`.

2018-01-16 23:43 UTC, psylone commented on app/helpers/questions_helper.rb
> +  def set_title(question)
Хорошо, только лучше назвать метод иначе поскольку по факту мы только читаем данные в нём и ничего не устанавливаем.

2018-01-16 23:43 UTC, psylone commented on app/helpers/tests_helper.rb
> +  "<a href='https://github.com/#{author}/#{repo}' target='blank'>Проект Тест Гуру</a>".html_safe
Стоит использовать метод `link_to`, он здесь доступен.

2018-01-16 23:43 UTC, psylone commented on app/views/layouts/application.html.erb
> +    <title><%= page_title %></title>
Можно использовать [такую штуку](http://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-content_for): `yield(:page_title) || 'Проект Тест Гуру'`, но можно и хэлпер оставить.

2018-01-16 23:43 UTC, psylone commented on app/views/layouts/application.html.erb
> +    <p id='<%= key %>'<%= value %></p>
Вот здесь лучше воспользоваться хэлпером [`tag`](http://api.rubyonrails.org/classes/ActionView/Helpers/TagHelper.html#method-i-tag).

2018-01-16 23:43 UTC, psylone commented on app/views/questions/_new_form.html.erb
> +<% end %>
Если ты сделал 2 разные формы для создания и редактирования из-за того что в форме редактирования `@test` не установлен, то это не проблема. Rails разрулит эту ситуацию так что лучше использовать единый фрагмент представления формы вопроса.

2018-01-16 23:43 UTC, psylone commented on app/views/questions/edit.html.erb
> +<%= content_for :page_title, set_title(@question) %>
Вообще, здесь должна быть вставка Ruby-кода без `=`: `<% ... %>` поскольку мы только устанавливаем заголовок страницы, а выводится он выше в главном шаблоне приложения.

На самом деле, здесь не нужно использовать `content_for`, потому что задача хэлпера из задания как раз вывести заголовок внутри шаблона. То есть, это должно быть вместо элемента `<h2>`.

2018-01-16 23:43 UTC, psylone commented on app/views/tests/show.html.erb
> +  <%= render @test.questions %>
Проверь правильно ли находится фрагмент представления для рендеринга вопроса здесь.

2018-01-17 02:09 UTC, v-kazantsev commented on app/views/questions/_new_form.html.erb
> +<% end %>
Сделал, но хочу заметить, что это все-таки разные формы, т.к. у них по-разному подписаны элементы. Насколько я понимаю, form.submit автоматически подписывает кнопку "edit" или "create", но она делает это по-английски.

2018-01-17 02:11 UTC, v-kazantsev commented on app/helpers/tests_helper.rb
> +  "<a href='https://github.com/#{author}/#{repo}' target='blank'>Проект Тест Гуру</a>".html_safe
Пытался, не пойму, как target = "blank" прикрутить.

2018-01-17 02:15 UTC, v-kazantsev commented on app/views/questions/edit.html.erb
> +<%= content_for :page_title, set_title(@question) %>
Получается, я неправильно понял задание, я устанавливал page_title а надо было header?

2018-01-17 03:34 UTC, merged

2018-01-18 12:03 UTC, psylone commented on app/views/questions/edit.html.erb
> +<%= content_for :page_title, set_title(@question) %>
Да, имелся в виду заголовок внутри содержания HTML страницы, не тот заголовок что в секции `<head>`.

2018-01-18 12:04 UTC, psylone commented on app/views/questions/_new_form.html.erb
> +<% end %>
Факт того что кнопки называются по-разному вовсе не означает что логически это разные формы. На самом деле, это одна и та же форма, просто лейблы имеют разные названия. Дальше это можно будет разрулить с помощью локализации, но сейчас вполне можно обойтись условным выражением или написать хэлпер вместо 2-х отдельных форм.

2018-01-18 12:04 UTC, psylone commented on app/helpers/tests_helper.rb
> +  "<a href='https://github.com/#{author}/#{repo}' target='blank'>Проект Тест Гуру</a>".html_safe
`link_to <name>, <target>, _target: :blank`.