Домашнее задание модуль 9
v-kazantsev/Test-guru pull request #8
Opened 2018-01-18 07:02 UTC by v-kazantsev

2018-01-18 22:51 UTC, psylone requested changes

2018-01-18 22:51 UTC, psylone commented on app/models/test_passage.rb
> +  before_validation :next_question
По факту оба обратных вызова отвечают за одну логику - назначить следующий вопрос, поэтому можно использовать единственный обратный вызов.

2018-01-18 22:51 UTC, psylone commented on app/models/test_passage.rb
> +  def calc_result
Лучше назвать просто `result`.

2018-01-18 22:51 UTC, psylone commented on app/views/test_passages/result.html.erb
> +<% end %>
Вообще, лучше сделать такой интерфейс: `<p>Результат: <%= test_passage_result %></p>`.

2018-01-18 22:51 UTC, psylone commented on app/views/test_passages/result.html.erb
> +<p>Результат: <%= tag.span class: set_color(@test_passage) do %>
На самом деле, хэлпер `set_color` ничего не устанавливает, то есть он не изменяет состояние объекта. Интерполяция да, но нет изменения состояния. Поэтому стоит назвать хэлпер иначе без префикса `set_`.

2018-01-18 22:51 UTC, psylone commented on app/views/test_passages/result.html.erb
> +<p><b><%= show_result(@test_passage) %></b></p>
Стоит отказаться от этого хэлпера. Нет ничего дурного если условное выражение используется для логики **вывода** в шаблоне.

2018-01-18 22:51 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +  def set_color(test_passage)
Ещё один момент с названием этого метода: `set_color`, но `passed` - явно не цвет.

2018-01-18 22:51 UTC, psylone commented on app/views/test_passages/show.html.erb
> +  (Question No <%= @test_passage.current_question_id %>
Не нужно полагаться на идентификатор (первичный ключ) для определения номера вопроса. Нет никаких гарантий что значения идентификатора будут следовать подряд без пропусков.

2018-01-18 22:51 UTC, psylone commented on app/views/test_passages/result.html.erb
> +<%= link_to 'К списку тестов', root_path %>
Лучше использовать хэлпер `tests_path`, потому что `root_path` может поменяться, а у нас здесь явно ссылка именно на список тестов.

2018-01-19 07:03 UTC, v-kazantsev commented on app/views/test_passages/show.html.erb
> +  (Question No <%= @test_passage.current_question_id %>
Я не вижу другого способа определить номер вопроса кроме как добавить счетчик в модель.

2018-01-20 01:42 UTC, psylone approved these changes

2018-01-20 01:42 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +    number_to_percentage(test_passage.result, precision: 0)
👍

2018-01-20 01:42 UTC, psylone commented on app/helpers/test_passages_helper.rb
>      end
Можно использовать факт что условное выражение - это выражение:

```ruby
color = if test_passage.result < 85
  'red'
else
  'green'
end
```

или воспользоваться тернарным выражением: `color = test_passage.result < 85 ? 'red' : 'green'`.

2018-01-20 01:42 UTC, psylone commented on app/views/test_passages/result.html.erb
> +<p>Результат: <%= test_passage_result(@test_passage) %>
Можно ещё добавить к названию метода `test_passage_result_amount` чтобы не возникало вопросов что это за хэлпер, учитывая что ниже вроде бы тоже выводится результат.

2018-01-20 01:42 UTC, psylone commented on app/views/test_passages/show.html.erb
> +  (Question No <%= @test_passage.current_question_id %>
Нормальный вариант, можно было добавить.

2018-01-20 01:55 UTC, merged