Домашнее задание модуль 10
v-kazantsev/Test-guru pull request #9
Opened 2018-01-22 06:31 UTC by v-kazantsev

2018-01-22 22:37 UTC, psylone requested changes

2018-01-22 22:37 UTC, psylone commented on app/controllers/sessions_controller.rb
> +    reset_session
Вероятнее всего, это будет зависеть от конкретной задачи, но можно не скидывать всю сессию, а только лишь удалять из неё идентификатор пользователя.

2018-01-22 22:37 UTC, psylone commented on app/helpers/application_helper.rb
> +    end
Подумай как можно обойтись без условного выражения и вместе с тем, выводить все имеющиеся на данный момент флэш-сообщения. Посмотри в сторону итераторов.

2018-01-22 22:37 UTC, psylone commented on app/helpers/application_helper.rb
> +    end
Также пожалуйста проверь ещё раз как работает данный хэлпер.

2018-01-22 22:37 UTC, psylone commented on app/views/layouts/application.html.erb
>      <% end %>
И этот фрагмент кода и `shared/links` являются по сути навигацией, их лучше держать в одном фрагменте представления. Кроме того, при чтении кода не вполне ясно что за ссылки в `shared/links`.

2018-01-22 22:37 UTC, psylone commented on app/views/layouts/application.html.erb
>      <% end %>
Ещё один показатель того что всё это должно быть в одном фрагменте - то что и здесь, и в `shared/links` вызывается `logged_in?`, хотя можно было бы обойтись единственным вызовом этого хэлпера.

2018-01-22 22:37 UTC, psylone commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
Можно разрешить просматривать список тестов пользователям без сессии.

2018-01-22 22:37 UTC, psylone commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
Я бы шёл обратным путём и указывал фильтр явно. Писать кода немного больше, но читается лучше.

2018-01-22 22:37 UTC, psylone commented on app/controllers/sessions_controller.rb
> +      byebug
Это явно лишнее.

2018-01-22 22:37 UTC, psylone commented on app/controllers/sessions_controller.rb
> +      end
Можно обойтись без флэш-сообщения и чуть упростить логику: `redirect_to cookies[:previous_url] || tests_path`.

2018-01-22 22:37 UTC, psylone commented on app/controllers/application_controller.rb
> +  before_action :set_cookie
Суть не в том что мы какую-то куку устанавливаем, а в том что мы именно устанавливаем `url` куда пользователь желает попасть.

2018-01-22 22:37 UTC, psylone commented on db/schema.rb
> +    t.index ["email"], name: "index_users_on_email", unique: true
👍

2018-01-22 22:37 UTC, psylone commented on app/controllers/tests_controller.rb
> +  @user = current_user
Нет смысла устанавливать инстанс переменную, метод `current_user` доступен в контроллерах, представлениях и хэлперах.

2018-01-23 03:31 UTC, v-kazantsev commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
Возникает вопрос - нужно ли показывать кнопки "Start" и "Create test" пользователям без сессии.

2018-01-23 04:57 UTC, v-kazantsev commented on app/helpers/application_helper.rb
> +      end.join.html_safe
Я не понимаю, почему здесь пришлось использовать html_safe если тут tag.p но без него выдается html код вместо сообщения.

2018-01-23 20:32 UTC, psylone commented on app/helpers/application_helper.rb
> +      end.join.html_safe
Потому что любая строка считается безопасной и выводится как есть. Для того чтобы шаблонизатор понял что эта строка является разметкой HTML и является безопасной необходимо указывать `html_safe`.

2018-01-23 20:32 UTC, psylone commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
Думаю что не нужно.

2018-01-23 20:59 UTC, psylone approved these changes

2018-01-23 20:59 UTC, psylone commented on app/views/shared/_nav_links.html.erb
> +<%= link_to 'Signup', signup_path %> |
Если у пользователя есть сессия, показывать ссылку на регистрацию смысла нет.

2018-01-24 03:19 UTC, merged

2018-01-24 03:28 UTC, v-kazantsev commented on app/helpers/application_helper.rb
> +      end.join.html_safe
safe_join(
        flash.map do |key, value|
          tag.p value, id: key
        end
        )

2018-01-24 03:29 UTC, v-kazantsev commented on app/helpers/application_helper.rb
> +      end.join.html_safe
так мне больше нравится